Add api key support for submit url
blinklabs-io/bluefin pull request #208
Opened 2024-07-08 13:17 UTC by mgpai22

Closes https://github.com/blinklabs-io/bluefin/issues/207

2024-07-08 13:23 UTC, agaffney submitted a review, later dismissed

2024-07-08 13:23 UTC, agaffney commented on internal/tx/tx.go
> +		req.Header.Add("project_id", cfg.Submit.UrlKey)
This header is specific to Blockfrost, but the config param is named generically. Instead, the config param should be have Blockfrost in the name (maybe `SUBMIT_BLOCKFROST_PROJECT_ID`), and then we can add support for other auth schemes later.

2024-07-08 13:23 UTC, wolf31o2 requested changes

2024-07-08 13:23 UTC, wolf31o2 commented on internal/config/config.go
> +	UrlKey     string `yaml:"urlKey"       envconfig:"SUBMIT_URL_KEY"`
This is ambiguous. Key for who? What? This would be better handled with generic "header" support, rather than a provider specific implementation.

2024-07-08 13:40 UTC, mgpai22 commented on internal/tx/tx.go
> +		req.Header.Add("project_id", cfg.Submit.UrlKey)
Didn't realize it was bf specific, thanks

2024-07-08 21:37 UTC, wolf31o2 requested changes

2024-07-08 21:37 UTC, wolf31o2 commented on internal/config/config.go
> +	BlockFrostProjectID string `yaml:"blockFrostProjectID"` envconfig:"SUBMIT_BLOCKFROST_PROJECT_ID"`
There's an extra ` in your code.
```suggestion
	BlockFrostProjectID string `yaml:"blockFrostProjectID" envconfig:"SUBMIT_BLOCKFROST_PROJECT_ID"`
```

2024-07-09 01:16 UTC, mgpai22 commented on internal/config/config.go
> +	BlockFrostProjectID string `yaml:"blockFrostProjectID"` envconfig:"SUBMIT_BLOCKFROST_PROJECT_ID"`
Fixed, thanks

2024-07-09 01:51 UTC, wolf31o2 approved these changes

2024-07-09 01:54 UTC, merged